name: learn-github-actions
on: [push, pull_request]
jobs:
    run-linter:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16.5'
            - run: npm install
            - run: npm run lint
